// Wraps the OpenNext worker to add the daily settlement cron.
// @ts-ignore Generated by `opennextjs-cloudflare build`.
import { default as handler } from "./.open-next/worker.js";

export default {
  fetch: handler.fetch,
  async scheduled(_event: ScheduledController, env: CloudflareEnv & { NEXT_PUBLIC_APP_URL: string; CRON_SECRET: string }, ctx: ExecutionContext) {
    const request = new Request(`${env.NEXT_PUBLIC_APP_URL}/api/jobs/settlement`, { headers: { authorization: `Bearer ${env.CRON_SECRET}` } });
    ctx.waitUntil(handler.fetch(request, env, ctx));
  },
} satisfies ExportedHandler<CloudflareEnv>;
